### ISSUE TITLE
Nebula not downloading from sine.

### ISSUE THREAD

**Issue by ApoorvPatidar** [JustAdumbPrsn/Zen-Nebula#295]
### ⚠️ Preliminary Checks

- [x] I have read and understood the contribution guidelines.
- [x] I have searched the existing issues and this is not a duplicate.
- [x] I have tested this without any other Zen Mods enabled.
- [x] I can confirm this bug is reproducible with Nebula and does not occur when Nebula is disabled.

### What happened?

Not able to download the Nebula from the sine marketplace on the zen browser. All the other downloads are working fine only having issue with nebula. 

### Nebula Version

NA

### Zen Browser Version

1.16.4b

### Operating System

Linux (AppImage)

### Affected Component(s)

Other

**Comment by AbirRazzak** [comment]
I can confirm I could download just fine from the marketplace. On Zen Browser 1.17.1b (Firefox 144.0) (64-bit) and Sine 2.2.3.

**Comment by JustAdumbPrsn** [comment]
@CosmoCreeper

**Comment by CosmoCreeper** [comment]
@ApoorvPatidar @AbirRazzak 
Run this:
```sudo chown $(whoami):$(whoami) -R ~/.zen/*/chrome/```

**Comment by JellyPeixe** [comment]
I don't know if this is related but all mods in the Sine Marketplace are showing the following error:

429: Too Many Requests For more on scraping GitHub and how it may affect your rights, please review our Terms of Service (https://docs.github.com/en/site-policy/github-terms/github-terms-of-service).

This error shows when you click the button on the left side of install. I don't know if this is a widespread GitHub issue.

**Comment by ErfanRasti** [comment]
> [@ApoorvPatidar](https://github.com/ApoorvPatidar) [@AbirRazzak](https://github.com/AbirRazzak) Run this: `sudo chown $(whoami):$(whoami) -R ~/.zen/*/chrome/`

This command fixed the issue for me.

**Comment by CosmoCreeper** [comment]
@JellyPeixe man everyone is having this issue now...

Currently the only fix for now is to use a VPN as I believe its an ISP issue.

**Comment by DariusSlowik** [comment]
Same for me. CachyOS x64 KDE Plasma 6. Just hangs on grayed out "Install". In chrome folder under sine-mods/Nebula, only Preferences.json and readme.md appear. Nothing else seem to change.
The command above didn't help.

<img width="428" height="374" alt="Image" src="https://github.com/user-attachments/assets/4fc844fa-4544-4987-9329-3d88a0cf6ba9" />

**Comment by CosmoCreeper** [comment]
Try installing v2.3.

**Comment by DariusSlowik** [comment]
@CosmoCreeper 
I tried installing v2.3 [multiple variants].
Firstly,
the "docs" link from releases leads to an old instructions of v0.1 [or v1.0].

Secondly,
the automatic installer from the v2.3c release fails to get required privilages. No matter if I run it as root or normal user. The only option from it that works is "Uninstallation".
Regular user:
<img width="963" height="224" alt="Image" src="https://github.com/user-attachments/assets/ca3038b6-0a15-4501-9430-4feea3b8b896" />

Root:
<img width="746" height="97" alt="Image" src="https://github.com/user-attachments/assets/b7673e06-b3d5-4ff7-9b81-420de5f7376c" />

Thirdly,
after following manual install instructions from main page, but swapping engine.zip from certain releases, the most I could get is the automatic intallator appearing on each Zen run asking for providing password and failing to gain privilages again and after skipping and turning the installer off, Sine is present in the settings but blank, no options or buttons work.

**Comment by DariusSlowik** [comment]
ok, @CosmoCreeper  after giving it one more go it works, and Nebula gets installed, but...
This is how Zen looks now:

<img width="1385" height="775" alt="Image" src="https://github.com/user-attachments/assets/b1280c11-9224-40d1-a345-e5f79e6a50a9" />

<img width="323" height="603" alt="Image" src="https://github.com/user-attachments/assets/011ffbd1-fce6-4f90-8076-22480dbcb5ab" />

<img width="476" height="867" alt="Image" src="https://github.com/user-attachments/assets/617f12c0-e4b6-4c45-8c20-8034ab167798" />

and Nebula doesn't work.
However, I guess you know about all this already ;)

**Comment by CosmoCreeper** [comment]
@DariusSlowik do you have a polkit agent and pkexec installed?
Is the agent running?

**Comment by DariusSlowik** [comment]
@CosmoCreeper 
<img width="699" height="309" alt="Image" src="https://github.com/user-attachments/assets/cd2adbe6-61a8-4f63-b1fd-3c35becfd5a1" />

<img width="223" height="92" alt="Image" src="https://github.com/user-attachments/assets/98335f68-da91-4055-b8cc-d819efc4ef98" />

yup.

**Comment by DariusSlowik** [comment]
@CosmoCreeper ok, I reinstalled the browser and the mod manager and the functionality works fine, I can add mods, etc and Nebula works.
However, after adding Sine, the issue with invisible text remains. I didn't find anything similar on the internet or in the issues.

**Comment by CosmoCreeper** [comment]
Invisible text in the Sine page likely means that locales are messed up.

Visit this url in your browser: chrome://locales/en-US/sine-preferences.ftl
Next, screenshot or copy the text in it and paste it here. That will tell me what all is going on.

**Comment by DariusSlowik** [comment]
chrome://locales/en-US/sine-preferences.ftl:
<img width="789" height="344" alt="Image" src="https://github.com/user-attachments/assets/8e464b47-0046-482f-9d63-236a9192f4b5" />

chrome://locales/pl-PL/sine-preferences.ftl - my language:
<img width="961" height="368" alt="Image" src="https://github.com/user-attachments/assets/969a0485-5497-4e3a-a639-d78f83de1130" />

It all just translates to "File not found" but in Polish.

One thing concrens me. "chrome://"? in mozilla? shouldn't it be like: "about:preferences" f.e?

**Comment by CosmoCreeper** [comment]
chrome://locales is where Sine stores locales, despite loading those into about:preferences.

Anyways, yeah it looks like your locales are messed up (non-existent). On v2.3c's release page, download and extract the locales.zip file into your chrome folder in Zen and see what happens.

**Comment by DariusSlowik** [comment]
Copied into profile chrome and into zen: /opt/zen-browser-bin/browser/chrome. Cleared out startup cache. Still the same: No file found.

**Comment by CosmoCreeper** [comment]
No the chrome folder is in your zen profile folder.

**Comment by DariusSlowik** [comment]
I copied to both. Copied to the 2nd one after copying to the zen profile folder when I saw the first action didn't work.

**Comment by CosmoCreeper** [comment]
Okay so in your profile's chrome folder, what is the directory structure now?

**Comment by DariusSlowik** [comment]
<img width="480" height="270" alt="Image" src="https://github.com/user-attachments/assets/a77689d4-b537-41d3-9a32-765f3aa829a8" />

**Comment by CosmoCreeper** [comment]
Whats inside of the JS folder? sine.uc.mjs or sine.sys.mjs?

**Comment by DariusSlowik** [comment]
sine.sys.mjs

<img width="557" height="346" alt="Image" src="https://github.com/user-attachments/assets/f5f2ed9b-58fa-4ac6-ba88-1221303b2b9b" />

EDIT:
I uninstalled Sine [with the installer (weird that only this option works on arch, it would seem like somewhere 'write' permissions are missing)], and the problem with invisible text disappeared disappeared.

**Comment by CosmoCreeper** [comment]
Oh okay. So its all working now?

**Comment by BISWA63** [comment]
@CosmoCreeper I tried the command you gave above, tried connecting to vpn (proton vpn free version), but still Nebula is not downloading, still greyed out button. (I am on ver 2.2.3)
(I am on CachyOS Hyprland)

**Comment by CosmoCreeper** [comment]
Try this Linux installer:
https://github.com/CosmoCreeper/Sine/actions/runs/21252078124/artifacts/5220427103

**Comment by BISWA63** [comment]
<img width="1895" height="1014" alt="Image" src="https://github.com/user-attachments/assets/1e00003c-27f5-48d1-86a6-d05fb3e77ad2" />


link the helper please

**Comment by CosmoCreeper** [comment]
Oh i knew this would be a problem. :(
Mb someone else built this version of the installer, ill have to fix it when I get a chance.

There is a manual installation guide available here:
https://github.com/sineorg/docs/tree/main/src/installation.md

**Comment by DariusSlowik** [comment]
> Oh okay. So its all working now?

Not exactly, I don't have Sine nor Nebula now and the problem is fixed.
I tried running the installer you send over, now it finishes with different error:

<img width="930" height="632" alt="Image" src="https://github.com/user-attachments/assets/de16c22b-ad39-483e-87e8-036557a33338" />

Edit:
reinstalled again (manually) and problem with missing text disappeared. So all fine for me. Installer still doesn't work tho.

**Comment by CosmoCreeper** [comment]
Yeah installer needs quite some work.
Glad to know it works now.

**Comment by BISWA63** [comment]
> Edit: reinstalled again (manually) and problem with missing text disappeared. So all fine for me. Installer still doesn't work tho.

Reinstalled what? sine or zen? I am also getting missing text issue

Edit: since you mentioned manually, I assume you mean sine by that
but I just installed sine manually and I am getting the same missing text issue
what did you do specifically to fix it? fyi I am using zen-browser-bin from cachyos repo, [link](https://packages.cachyos.org/package/cachyos/x86_64/zen-browser-bin)

**Comment by DariusSlowik** [comment]
> > Edit: reinstalled again (manually) and problem with missing text disappeared. So all fine for me. Installer still doesn't work tho.
> 
> Reinstalled what? sine or zen? I am also getting missing text issue

sine. Uninstalled it completely with the installer and installed manually from the [manual](https://github.com/sineorg/docs/tree/main/src/installation.md)

> Edit: since you mentioned manually, I assume you mean sine by that
> but I just installed sine manually and I am getting the same missing text issue
> what did you do specifically to fix it? fyi I am using zen-browser-bin from cachyos repo, [link](https://packages.cachyos.org/package/cachyos/x86_64/zen-browser-bin)

I am using the same build - CachyOS and zen-browser-bin from their repo.
Uninstall sine completely (the installer helps). Install again manually from the instructions provided above. Also, use the newest version of v2.3c of Sine. Available on the [github](https://github.com/CosmoCreeper/Sine/releases/tag/v2.3c).
The text reappeared and could download Nebula.

Edit:
make sure you are using the newest program.zip and profile.zip

**Comment by BISWA63** [comment]
that did not fix for me, the scripts did not work for my uninstallation, it prompted with a failure message, so I manually uninstalled by following the manual and installed v2.3c as you said, but that did not fix the issue for me.
I can reinstall zen but I would rather not to, instead I will just wait for an update of Sine, Thankyou for your time invested tho, maybe that could help someone else.

**Comment by DariusSlowik** [comment]
what does your file structure looks like in:
1. /opt/zen-browser-bin/
2. /opt/zen-browser-bin/default/pref/
3. ~/.zen/[profile]/chrome/
4. ~/.zen/[profile]/chrome/JS
Did you clean startup cache?

**Comment by BISWA63** [comment]
I deleted the 2 config.js files inside 1. and 2. , Everything else is just normal I believe
I started on a fresh profile just for testing sine and exactly followed the uninstallation and installation manual and yes I did clean startup cache

**Comment by DariusSlowik** [comment]
Could you please take screenshots how this looks after the installation? (The locations). Do you have english set in zen or some other language?

Uninstallation of zen through paru shouldn't take away your settings (backup profile folder before, please) you should try.

**Comment by BISWA63** [comment]
Sure let me give it a shot, hold up

**Comment by BISWA63** [comment]
<img width="1918" height="1038" alt="Image" src="https://github.com/user-attachments/assets/6aef2b6f-3afe-4658-b9d4-9f3d92797aea" />

<img width="1918" height="1078" alt="Image" src="https://github.com/user-attachments/assets/433cf315-bed0-4174-b4bf-810ac6a2fadc" />


Nahh, didn't fix
Fresh Install, English language

**Comment by DariusSlowik** [comment]
ah. Don't extract insides of "locales" folder into chrome. Extract folder "locales" into "chrome".
Like this:

<img width="813" height="404" alt="Image" src="https://github.com/user-attachments/assets/35e4c316-fdc2-4c08-8083-fdbabda63b77" />

**Comment by BISWA63** [comment]
oh my fucking god I am such a dumbfuck!
Thankyou soo much dude that fixed it, till now I was extracting the files using Nautilus (GNOME Files app) which automatically creates subfolders for zip files after extracting with the same name if it does not already exists inside the zip, so it did not create a subfolder for locales because it already had one inside the zip, so I was copying over the contents inside of the subfolders like a madman without checking the actual contents inside of it and it broke my shit
TYSM MAN ILY FR.
@CosmoCreeper Installer is broken but everything works fine in v2.3c, Thankyou

**Comment by CosmoCreeper** [comment]
Yeah no problem. I always appreciate the people who try to help out with others while I'm busy, so thank you @DariusSlowik!

The installers will be fixed as soon as possible, although I'm still not sure **exactly** when.

**Comment by AyanaayaW** [comment]
I'm having the same issue from MacOS! Can anyone help me fix it? Thanks

**Comment by CosmoCreeper** [comment]
Are you unable to click the install button as it greys out?

**Comment by AyanaayaW** [comment]
<img width="211" height="250" alt="Image" src="https://github.com/user-attachments/assets/845a8fb6-596a-4f65-99a4-da3487e5b64c" />

yup!

**Comment by CosmoCreeper** [comment]
Try v2.3c.
